# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JenkinsDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Fabric'
  pod 'Crashlytics'

  target 'JenkinsDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JenkinsDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
