# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

before_all do
  ENV['DEVELOPER_DIR'] = '/Applications/Xcode.app/Contents/Developer'
  skip_docs
  update_fastlane
  clear_derived_data
end

default_platform(:ios)

platform :ios do
  desc "Lauch simulator and run application."
  lane :tests do
	run_tests(workspace: "JenkinsDemo.xcworkspace",
            devices: ["iPhone 5s"],
            scheme: "JenkinsDemo")
  end
end
